### ISSUE TITLE
Add gulp task for devServer to package.json...

### ISSUE THREAD

**Issue by ohritz** [preciofishbone/OmniaFx-Demos#2]

**Comment by andtii** [comment]
@ohritz What is the issue? did you run gulp omnia-serve. I just tried getting the demo project fresh from github, npm install and it worked using gulp omnia-serve?

**Comment by ohritz** [comment]
What do you say to add the omnia-serve and omnia-bundle to the projects package json unders scripts?
like 
```
"dev": "gulp omnia-serve",
"bundle": "gulp omnia-bundle"
```
any other tasks worth adding?

**Comment by andtii** [comment]
@ohritz yea you can add it up, currently its only thoose 2
